export const FETCH_WORKSPACES_DATA 					= 'FETCH_WORKSPACES_DATA';
export const FETCH_WORKSPACES_DATA_SUCCESS 			= 'FETCH_WORKSPACES_DATA_SUCCESS';
export const FETCH_WORKSPACES_DATA_FAILURE 			= 'FETCH_WORKSPACES_DATA_FAILURE';
export const SORT_WORKSPACES_DATA                   = 'SORT_WORKSPACES_DATA';